name: publish.yml
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: docker.io/tikaiz/website-frontend:latest
